version: '2'
services:
    blog_cms-app:
        image: blog_cms
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://blog_cms-mysql:3306/blog_cms?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    blog_cms-mysql:
        extends:
            file: mysql.yml
            service: blog_cms-mysql
